### ISSUE TITLE
Criar a Home da Wiki

### ISSUE THREAD

**Issue by DanielPortods** [Interacao-Humano-Computador/2020.2-Ingresso.eear#4]
## Descrição
Issue direcionada para a adição da página home da Wiki do projeto.
## Tarefas
- [x] Inserir uma descrição do projeto;
- [x] inserir os colaboradores;
- [x] inserir a motivação da escolha do site.

## Critérios de Aceitação
- [x] A página home está publicada e devidamente revisada.

**Comment by Bruno-Felix** [comment]
@DenysRogeres joga na roda sua atividade sobre o site, por obsequio.
